<section class="vh-100 bg-image"
    style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body p-5">
                            <h2 class="text-uppercase text-center mb-5">Weather App</h2>
                            <?php echo $this->tag->form("index/weather"); ?>
                            <div class="form-outline mb-4">
                                <label class="form-label" for="form3Example4cdg" name='city'>Enter City</label>
                                <input type="text" id="form3Example4cdg" name='city'
                                    class="form-control form-control-lg" />
                            </div>
                            <label for="type">Choose:</label>

                            <select name="type" id="type">
                                <option value="/current.json">Current weather</option>
                                <option value="/forecast.json">Forecast</option>
                                <option value="/history.json">History</option>
                                <option value="/timezone.json">Time Zone</option>
                                <option value="/sports.json">Sports</option>
                                <option value="/astronomy.json">Astronomy</option>
                            </select>
                            <div class="d-flex justify-content-center">
                                <button type="submit"
                                    class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Get
                                    Weather</button>
                            </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
